### ISSUE TITLE
Support alpine Docker image environment

### ISSUE THREAD

**Issue by mschuchard** [pmq20/ruby-packer#37]
I am trying to create a Docker image for this as it would be very useful in multi-stage builds for Ruby software or with e.g. OpenFaaS. Unfortunately, it seems to not be usable in an Alpine linux image.

A simple image file:

```dockerfile
ARG rubyvers
FROM ruby:${rubyvers}-alpine
RUN apk add --no-cache squashfs-tools gcc make curl ca-certificates && curl -L http://enclose.io/rubyc/rubyc-linux-x64.gz | gunzip > /usr/bin/rubyc && chmod +rx /usr/bin/rubyc
RUN rubyc
```

yields:

> /bin/sh: rubyc: not found

Note that the same error results from providing a full path to `rubyc`.

Debugging the image with a statically compiled/linked goss go binary:

```dockerfile
RUN curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64 -o /usr/bin/goss
RUN goss
```

works correctly and proves there is some kind of incompatibility here.

**Comment by drbrain** [comment]
I've seen this same issue building go binaries on the `ubuntu:16.04` image and trying to run them on the `alpine:latest` image.

Some googling suggests [installing `libc6-compat`](https://serverfault.com/questions/883625/alpine-shell-cant-find-file-in-docker#comment1139245_883625) may allow you to run `rubyc`?

**Comment by mschuchard** [comment]
Looked into those glibc dynamic linking workarounds and they do not seem to be working in this situation.

Should I be looking into other software for lightweight Ruby software packaging and containerization, or is there interest in first party support for this?

I know Hashi just released a Vagrant version packaged with AppImage so that route may work.

**Comment by drbrain** [comment]
I don't know what is different about the alpine linux environment and unfortunately I don't have the time to figure out how to get the packaged rubyc to work in it.

You can define a Dockerfile that builds rubyc under alpine, then uses that rubyc to package your application, then copies the packaged application to a standalone image.  I have added some instructions for [building rubyc yourself](https://github.com/pmq20/ruby-packer#building-rubyc-yourself) to the README that may get you started.

Since you need the same toolchain for building your own rubyc and for packaging your application with rubyc the main downside is the extra time spent building rubyc.  Of course, you can store your alpine-compatible rubyc to save time.

**Comment by mschuchard** [comment]
Sure, if the AppImage route does not work I will look at building rubyc with musl links.
Thanks.

**Comment by drbrain** [comment]
Great, thanks for the feedback, and let us know if we can improve the build instructions!
