### ISSUE TITLE
Has the project been abandoned?

### ISSUE THREAD

**Issue by kke** [pmq20/ruby-packer#77]
Master has been broken for 7+ months.

For example, the PR #44 that fixes an obvious typo that breaks the tool has not been merged.

@pmq20 have you given up on this? This is an awesome and important project for the ruby ecosystem and should be maintained, if not by you, someone.

**Comment by d4rky-pl** [comment]
@pmq20 Hey, I know _everybody_ hates these sort of comments but I'm running an internal tool that I've already invested dozens of hours into that uses this packer as a last step and I'd love to know a definitive answer:

Is this project dead or in maintenance only mode? Can we ever expect newer Ruby version, Bundler 2.x support or fixing any of the outstanding issues / accept any of the pending PRs? Or should we fork / look for an alternative? (which is totally fine, you're entitled to drop your own project!)

**Comment by kallisti5** [comment]
Authors abandoning their open source projects, so hot right now.

**Comment by mamccr** [comment]
> Authors abandoning their open source projects, so hot right now.
> 
> Seeing a lot of these projects lately... Really not sure why so many authors are pumping and dumping projects. I'd recommend forking and renaming if you use this. With 50+ forks all with the same name on Github, "who is really maintaining something" gets sketchy.
> 
> Ideally though the original author would pick " a few people contributing valuable PR's " and give them owner status of the repo. I've had good luck with that strategy on a few projects i've lost free time to manage.

Snarky! People "pump and dump" projects because they're human beings with lives. Life circumstances change. People have kids, get sick, get in accidents, have to start taking care of ailing parents and grandparents, take on jobs with more responsibility, leave jobs with a lot of responsibility, get burned out, etc. etc. It doesn't matter why. As consumers of anything someone is giving away, I think our only reaction should be gratitude for the part of their lives they gave with good intention and made freely available. I'd even go so far as to say that it's not just the kind thing to do (which is enough of a reason by itself), but that our own personal happiness depends on it.

**Comment by kallisti5** [comment]
My point was, if you don't see yourself continuing something, and are able, communicate that to encourage forks (read only is a single button press)

**Comment by mamccr** [comment]
Fair enough. In my experience, the letting go of something you've committed time to can be a bit of a limbo process. "Maybe I'll get some time next week," you might say to yourself, but then it doesn't materialize. Sometimes it's hard to know. But I agree that asking for help from others is a healthy thing to do. It's just hard to make that admission sometimes. Perhaps more nuanced, gentle encouragement for someone to move in that direction is a better approach.

**Comment by pmq20** [comment]
@d4rky-pl Sorry for the delayed reply:
1. The project is not dead.
2. Yes, I plan to maintain support for the latest Ruby version, to keep the enclosed Ruby version in sync with the official one. The old Ruby versions probably won't be supported, though.
3. Bundler is a part of Ruby's standard library since Ruby 2.6. It will be kept up to date as long as the enclosed Ruby is kept up to date.
4. I am attending to reported issues one by one, ordered by creation time descendingly.
5. Please feel free to fork it. Derived projects are totally fine and actually encouraged since the project is [MIT licensed](https://github.com/pmq20/ruby-packer/blob/master/LICENSE)

**Comment by pmq20** [comment]
@kallisti5 @mamccr Thank you for the kind suggestion! I have updated the README with the latest maintenance status to keep everbody informed:

> **MAINTENENCE STATUS** (Jun 27th, 2020): This project's original author [Minqi Pan](https://github.com/pmq20/ruby-packer/blob/master/README.md) is currently only available to maintain this project during his weekend. We are working with the goal of releasing next version `rubyc v2.7.1a` as soon as possible; please see [CHANGELOG.md](https://github.com/pmq20/ruby-packer/blob/master/CHANGELOG.md) for the details of the upcoming release. Also, we are attending to reported issues one by one, ordered by creation time descendingly.

**Comment by d4rky-pl** [comment]
@pmq20 thanks for the update, really appreciated!
